apiVersion: apps/v1
kind: Deployment
metadata:
  name: dogsapp
  labels:
    app: dogsapp
spec:
  replicas: 10
  selector:
    matchLabels:
      app: dogsapp
  template:
    metadata:
      labels:
        app: dogsapp
    spec:
      containers:
      - name: dogsapp
        image: dogsapp:latest
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 3000